c_stdlib_version:          # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]
  - "2.17"                 # [linux]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]
